In [1]:
import pandas as pd
import json
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
import random
import string
import re
#tokenize and remove stopword
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
stop_words = set(stopwords.words('english')) 
from nltk.stem.snowball import SnowballStemmer

In [2]:
with open('A:/PWR/project/SMA/News_Category_Dataset_v2.json') as f:
    data = pd.DataFrame(json.loads(line) for line in f)
pd.set_option('max_colwidth', 1000)    
data

authors  \
0                                                                                     Melissa Jeltsen   
1                                                                                       Andy McDonald   
2                                                                                          Ron Dicker   
3                                                                                          Ron Dicker   
4                                                                                          Ron Dicker   
5                                                                                          Ron Dicker   
6                                                                                          Ron Dicker   
7                                                                                     Todd Van Luling   
8                                                                                       Andy McDonald   
9                                                                                     Todd Van Luling   
10                                                                                  Sebastian Murdock   
11                                                                                                      
12                                                                                      Karen Pinchin   
13                                                                       Elise Foley and Roque Planas   
14                                                                        Michael Isikoff, Yahoo News   
15                                                                                     Mary Papenfuss   
16                                                                                     Mary Papenfuss   
17                                                                                      Laura Bassett   
18                                                                                     Chris D'Angelo   
19                                                                                     Mary Papenfuss   
20                                                                                         David Moye   
21                                                                                      Andy McDonald   
22                                                                                      Hilary Hanson   
23                                                              Josh Smith and Christine Kim, Reuters   
24                                                                                                      
25                                                                                   Antonia Blumberg   
26                                                                                                      
27                                                                                  Sebastian Murdock   
28                                                                                        Kenya Downs   
29                                                                                  Sebastian Murdock   
...                                                                                               ...   
200823                                                              Michelangelo Signorile, Columnist   
200824                                                                                                  
200825             Larry Bock, Contributor\nFounder and Organizer, USA Science & Engineering Festival   
200826                     Sarah Costa, Contributor\nExecutive Director of Women's Refugee Commission   
200827                                                                                                  
200828                                                                                                  
200829                                                                                                  

In [3]:
def removeNonAscii(s): 
    return "".join(i for i in s if ord(i)<128)

In [4]:
author=[]
for a in data['authors']:
    auth=removeNonAscii(a.lower())
    author.append(auth)

categ=[]
for b in data['category']:
    cat=removeNonAscii(b.lower())
    categ.append(cat)
    
headlines=[]
for c in data['headline']:
    hl=removeNonAscii(c.lower())
    headlines.append(hl)
    
short=[]
for d in data['short_description']:
    sd=removeNonAscii(d.lower())
    short.append(sd)

In [5]:
clean = pd.DataFrame(dict(authors=author, category=categ, headline=headlines, short_description=short)) 

In [6]:
#clean.to_csv('A:/PWR/project/SMA/dataclean.csv')

In [3]:
dataset = pd.read_csv('A:/PWR/project/SMA/data.csv')
dataset

id  category  \
0          1  business   
1          2  business   
2          3  business   
3          4  business   
4          5  business   
5          6  business   
6          7  business   
7          8  business   
8          9  business   
9         10  business   
10        11  business   
11        12  business   
12        13  business   
13        14  business   
14        15  business   
15        16  business   
16        17  business   
17        18  business   
18        19  business   
19        20  business   
20        21  business   
21        22  business   
22        23  business   
23        24  business   
24        25  business   
25        26  business   
26        27  business   
27        28  business   
28        29  business   
29        30  business   
...      ...       ...   
13620  13621    travel   
13621  13622    travel   
13622  13623    travel   
13623  13624    travel   
13624  13625    travel   
13625  13626    travel   
13626  13627    travel   
13627  13628    travel   
13628  13629    travel   
13629  13630    travel   
13630  13631    travel   
13631  13632    travel   
13632  13633    travel   
13633  13634    travel   
13634  13635    travel   
13635  13636    travel   
13636  13637    travel   
13637  13638    travel   
13638  13639    travel   
13639  13640    travel   
13640  13641    travel   
13641  13642    travel   
13642  13643    travel   
13643  13644    travel   
13644  13645    travel   
13645  13646    travel   
13646  13647    travel   
13647  13648    travel   
13648  13649    travel   
13649  13650    travel   

                                                                                                  headline  \
0                                      u.s. launches auto import probe, china vows to defend its interests   
1                           starbucks says anyone can now sit in its cafes -- even without buying anything   
2                seattle passes controversial new tax on city's biggest companies to combat housing crisis   
3                           uber ends forced arbitration in individual cases of sexual assault, harassment   
4                                chili's hit by data breach, credit and debit card information compromised   
5                                                            how uber silences women after sexual assaults   
6                                                                    how amazon is holding seattle hostage   
7                                bank of america appears to flip on firearm promise with loan to remington   
8                                        ex-volkswagen ceo charged in u.s. over emissions cheating scandal   
9                        women describe rampant groping, sexual harassment at verizon-contracted warehouse   
10                                                       t-mobile agrees to acquire sprint for $26 billion   
11                       the sec just made the case for divesting from fossil fuel companies much stronger   
12                                     dick's sporting goods is destroying its unsold assault-style rifles   
13             facebook didnt seem to care i was being sexually harassed until i decided to write about it   
14                       in los angeles, bitter tensions over where to house the homeless rile communities   
15                                                              the libertarian political movement is dead   
16                                      apple co-founder steve wozniak ditches facebook after data scandal   
17                                      twitter has suspended 1.2 million accounts for 'terrorist content'   
18                                    trump proposes slapping $100 billion in new tariffs on chinese goods   
19                                                                     the facebook apology tour continues   
20                                                     saks, lord & taylor hit by payme

### PREPROCESSING

In [5]:
#PREPROSESSING
def strip_links(text):
    link_regex    = re.compile("([^-_a-zA-Z0-9!@#%&=,/'\";:~`\$\^\*\(\)\+\[\]\.\{\}\|\?\<\>\\]+|[^\s]+)")
    links         = re.findall(link_regex, text)
    for link in links:
        text = text.replace(link[0], ', ')    
    return text

def drop_digits(in_str):
    digit_list = "1234567890"
    for char in digit_list:
        in_str = in_str.replace(char, "")
    return in_str

def strip_all_entities(text):
    entity_prefixes = ['@','#']
    for separator in  string.punctuation:
        if separator not in entity_prefixes :
            text = text.replace(separator,' ')
    words = []
    for word in text.split():
        word = word.strip()
        if word:
            if word[0] not in entity_prefixes:
                words.append(word)
    return ' '.join(words)

def stemmers(text):
    text = text.split()
    stemmer = SnowballStemmer('english')
    stemmed_words = [stemmer.stem(word) for word in text]
    text = " ".join(stemmed_words)

    # Return a list of words
    return(text)

In [6]:
headlines2=[]
for c2 in dataset['headline']:
    hl2=strip_all_entities(drop_digits(strip_links(c2)))
    headlines2.append(hl2)

In [7]:
short2=[]
for d2 in dataset['short_desc']:
    sd2=stemmers(strip_all_entities(drop_digits(strip_links(d2))))
    short2.append(sd2)

In [8]:
preproses = pd.DataFrame(dict(category=dataset.category, headline=headlines2, short_desc=short2)) 
preproses


category  \
0      business   
1      business   
2      business   
3      business   
4      business   
5      business   
6      business   
7      business   
8      business   
9      business   
10     business   
11     business   
12     business   
13     business   
14     business   
15     business   
16     business   
17     business   
18     business   
19     business   
20     business   
21     business   
22     business   
23     business   
24     business   
25     business   
26     business   
27     business   
28     business   
29     business   
...         ...   
13620    travel   
13621    travel   
13622    travel   
13623    travel   
13624    travel   
13625    travel   
13626    travel   
13627    travel   
13628    travel   
13629    travel   
13630    travel   
13631    travel   
13632    travel   
13633    travel   
13634    travel   
13635    travel   
13636    travel   
13637    travel   
13638    travel   
13639    travel   
13640    travel   
13641    travel   
13642    travel   
13643    travel   
13644    travel   
13645    travel   
13646    travel   
13647    travel   
13648    travel   
13649    travel   

                                                                                            headline  \
0                                  u s launches auto import probe china vows to defend its interests   
1                        starbucks says anyone can now sit in its cafes even without buying anything   
2          seattle passes controversial new tax on city s biggest companies to combat housing crisis   
3                      uber ends forced arbitration in individual cases of sexual assault harassment   
4                           chili s hit by data breach credit and debit card information compromised   
5                                                      how uber silences women after sexual assaults   
6                                                              how amazon is holding seattle hostage   
7                          bank of america appears to flip on firearm promise with loan to remington   
8                                   ex volkswagen ceo charged in u s over emissions cheating scandal   
9                   women describe rampant groping sexual harassment at verizon contracted warehouse   
10                                                     t mobile agrees to acquire sprint for billion   
11                 the sec just made the case for divesting from fossil fuel companies much stronger   
12                               dick s sporting goods is destroying its unsold assault style rifles   
13       facebook didnt seem to care i was being sexually harassed until i decided to write about it   
14                  in los angeles bitter tensions over where to house the homeless rile communities   
15                                                        the libertarian political movement is dead   
16                                apple co founder steve wozniak ditches facebook after data scandal   
17                                      twitter has suspended million accounts for terrorist content   
18                                   trump proposes slapping billion in new tariffs on chinese goods   
19                                                               the facebook apology tour continues   
20                                                  saks lord taylor hit by payment card data breach   
21                        international health group drops partnership with heineken over beer girls   
22                           myfitnesspal security breach affects million users under armour reports   
23                                  these stock photos show masculinity is more than biceps and beer   
24                                                      trapped inside the monster energy frat house   
25                               there are psychological reasons parents are so obsessed with target   
26                  

### TF-IDF

In [9]:
news_vectorizer = TfidfVectorizer(stop_words='english')
news_matrix = news_vectorizer.fit_transform(preproses.short_desc)
print 'There are '+ str(news_matrix.get_shape()[0]) + ' documents over a vocabulary feature space of ' + str(news_matrix.get_shape()[1]) + ' terms.'

tfidf = pd.DataFrame(news_matrix.toarray(), index=[preproses.headline, preproses.category], columns= news_vectorizer.get_feature_names())
tfidf

There are 13650 documents over a vocabulary feature space of 14563 terms.


aaaargh  \
headline                                                                                      category            
u s launches auto import probe china vows to defend its interests                             business      0.0   
starbucks says anyone can now sit in its cafes even without buying anything                   business      0.0   
seattle passes controversial new tax on city s biggest companies to combat housing crisis     business      0.0   
uber ends forced arbitration in individual cases of sexual assault harassment                 business      0.0   
chili s hit by data breach credit and debit card information compromised                      business      0.0   
how uber silences women after sexual assaults                                                 business      0.0   
how amazon is holding seattle hostage                                                         business      0.0   
bank of america appears to flip on firearm promise with loan to remington                     business      0.0   
ex volkswagen ceo charged in u s over emissions cheating scandal                              business      0.0   
women describe rampant groping sexual harassment at verizon contracted warehouse              business      0.0   
t mobile agrees to acquire sprint for billion                                                 business      0.0   
the sec just made the case for divesting from fossil fuel companies much stronger             business      0.0   
dick s sporting goods is destroying its unsold assault style rifles                           business      0.0   
facebook didnt seem to care i was being sexually harassed until i decided to write about it   business      0.0   
in los angeles bitter tensions over where to house the homeless rile communities              business      0.0   
the libertarian political movement is dead                                                    business      0.0   
apple co founder steve wozniak ditches facebook after data scandal                            business      0.0   
twitter has suspended million accounts for terrorist content                                  business      0.0   
trump proposes slapping billion in new tariffs on chinese goods                               business      0.0   
the facebook apology tour continues                                                           business      0.0   
saks lord taylor hit by payment card data breach                                              business      0.0   
international health group drops partnership with heineken over beer girls                    business      0.0   
myfitnesspal security breach affects million users under armour reports                       business      0.0   
these stock photos show masculinity is more than biceps and beer                              business      0.0   
trapped inside the monster energy frat house                                                  business      0.0   
there are psychological reasons parents are so obsessed with target                           business      0.0   
walmart partners with conservative group to remove cosmo from checkout lines                  business      0.0   
uber halts self driving car tests in california where it didn t test much anyway              business      0.0   
remington files for chapter bankruptcy amid mounting pressure for more gun control            business      0.0   
elon musk s estranged father has child with stepdaughter says it s god s plan                 business      0.0   
...                                                                                                         ...   
sumptuous suites for your sweetheart photos                                                   travel        0.0   
the gay traveler flash sales take on the hotel industry                                       travel        0.0   
diane disney miller remembers dad walt s secret disneyland apartment his passio

### DATA TESTING & TRAINING

In [10]:
training_data=tfidf.iloc[:-350]
training_label=preproses.category.iloc[:-350]
testing_data=tfidf.iloc[-350:]
testing_label=preproses.category.iloc[-350:]
testing_title=preproses.headline.iloc[-350:]

### KNN n=170

In [11]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=170, metric='cosine')

#Train the model using the training sets
knn.fit(training_data, training_label)

#Predict the response for test dataset
y_pred = knn.predict(testing_data)
#print(y_pred)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(testing_label, y_pred))

('Accuracy:', 0.64)


In [15]:
#print(y_pred)

In [16]:
tampil2= pd.DataFrame(columns=["headline","category","category_predicted"])
i=1
while i<=350:
    #prediction = knn.predict(testing_data[i-1:i])
    tampil2= tampil2.append({"headline":list(testing_title[i-1:i]), "category":list(testing_label[i-1:i]),"category_predicted":knn.predict(testing_data[i-1:i]) }, ignore_index=True)
    i=i+1

#tampil2.to_csv('A:/PWR/project/SMA/knn.csv')
tampil2.head()

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(testing_label, y_pred))
print(classification_report(testing_label, y_pred))

[[28  5  2  0  8  7  0]
 [ 4 35  3  1  6  1  0]
 [ 4  4 24  4  2 11  1]
 [ 0  2  1 45  0  2  0]
 [10  2  4  2 27  4  1]
 [ 5  5  4  0  3 33  0]
 [ 2  2  4  5  2  3 32]]
               precision    recall  f1-score   support

     business       0.53      0.56      0.54        50
        crime       0.64      0.70      0.67        50
entertainment       0.57      0.48      0.52        50
 food & drink       0.79      0.90      0.84        50
     politics       0.56      0.54      0.55        50
       sports       0.54      0.66      0.59        50
       travel       0.94      0.64      0.76        50

    micro avg       0.64      0.64      0.64       350
    macro avg       0.65      0.64      0.64       350
 weighted avg       0.65      0.64      0.64       350



### NBC

In [18]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(training_data, training_label)

#### NBC ACCURACY

In [19]:
predicted2 = clf.predict(testing_data)
#print(predicted)
np.mean(predicted2 == testing_label)

0.6685714285714286

In [19]:
#print(predicted2)

In [20]:
# jumlah testing data yg diambil hanya 5, dan melihat tetangganya siapa saja
tampil= pd.DataFrame(columns=["headline","category","category_predicted"])
l=1
while l<=100:
    prediction = clf.predict(testing_data[l-1:l])
    tampil= tampil.append({"headline":list(testing_title[l-1:l]), "category":list(testing_label[l-1:l]),"category_predicted":clf.predict(testing_data[l-1:l]) }, ignore_index=True)
    l=l+1

In [21]:
#tampil.to_csv('A:/PWR/project/SMA/NBC.csv')
tampil.head()

headline  \
0                [european debt crisis in spain soaring joblessness fuels barter economy]   
1  [jamie dimon beware the wall street journal says it is time to break up the big banks]   
2                                                     [influencer of the week jeremy lin]   
3                                                [the disingenuous economics of ron paul]   
4               [why inequality matters the housing crisis our justice system capitalism]   

     category category_predicted  
0  [business]         [business]  
1  [business]         [business]  
2  [business]           [sports]  
3  [business]         [business]  
4  [business]         [politics]

In [22]:
print(confusion_matrix(testing_label, predicted2))
print(classification_report(testing_label, predicted2))

[[32  3  2  0  8  4  1]
 [ 4 37  1  0  6  1  1]
 [ 5  5 26  3  1  3  7]
 [ 1  0  0 46  0  0  3]
 [18  3  0  1 25  1  2]
 [ 6  6  3  1  1 31  2]
 [ 6  1  2  3  1  0 37]]
               precision    recall  f1-score   support

     business       0.44      0.64      0.52        50
        crime       0.67      0.74      0.70        50
entertainment       0.76      0.52      0.62        50
 food & drink       0.85      0.92      0.88        50
     politics       0.60      0.50      0.54        50
       sports       0.78      0.62      0.69        50
       travel       0.70      0.74      0.72        50

    micro avg       0.67      0.67      0.67       350
    macro avg       0.69      0.67      0.67       350
 weighted avg       0.69      0.67      0.67       350



In [24]:
from sklearn.naive_bayes import GaussianNB
clf2 = GaussianNB()
clf2.fit(training_data, training_label)

predicted3 = clf2.predict(testing_data)
#print(predicted)
np.mean(predicted3 == testing_label)

0.4085714285714286